book_flask/src/routes/auth_routes.py
from flask import Blueprint, request, redirect, render_template, url_for
from flask_login import login_user, logout_user, login_required
from services.auth_service import register_user, authenticate_user
from logger import logger

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        found_user = authenticate_user(request.form['username'], request.form['password'])
        if found_user:
            login_user(found_user)
            next = request.args.get('next', None)
            if next:
                return redirect(next)
            return redirect(url_for('home', name=found_user.username))
        return "Invalid credentials", 401
    return render_template('content/login.html')

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if register_user(username, password):
            return redirect(url_for('auth.login'))
        return "User already exists", 400
    return render_template('content/register.html')

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home'))

book_flask/src/routes/book_routes.py
from crypt import methods

from flask import Blueprint, render_template, request, jsonify, redirect, url_for
from flask_login import login_required, current_user

from logger import logger
from models.constants import BookStatus
from services.book_service import test_data, update_user_book, get_books_by_query, generate_book_from_g_data, \
    get_book_by_g_id, get_books_by_user_id
from services.db import db
from models.book import Book
from utils.utils import output_request_info

book_bp = Blueprint('book', __name__)

@login_required
@book_bp.route('/books/mybooks')
def my_books():
    return "hi"


@book_bp.route('/my-archives')
@login_required
def my_archives():
    # books = db.session.query(Book).join(Book.users).filter(User.id == current_user.id).all()
    all_books = get_books_by_user_id(current_user.id)
    return render_template('parent/my-archives.html',
                           all_books=all_books,
                           owned_books=[owned for owned in all_books if owned.owned],
                           want_to_read=[wtr for wtr in all_books if wtr.status == BookStatus.WANT_TO_READ],
                           read_books=[read for read in all_books if read.status == BookStatus.READ],
                           next=url_for('book.my_archives'))

@book_bp.route('/search-catalog')
def search_catalog():
    return render_template('parent/catalog-search.html', books=[], next=url_for('book.search_catalog'))

@book_bp.route('/update-catalog')
def update_catalog():
    query = request.args.get("q", "").lower()
    template_books = []
    if query:
        books = get_books_by_query(query)
        for book in books['items']:
            template_books.append(generate_book_from_g_data(book))
    return render_template('layout/book-grid-modal.html', books=template_books)

@book_bp.route('/my-shelf')
@login_required
def my_shelf():
    test_books = get_books_by_user_id(current_user.id)
    return render_template('parent/my-shelf.html', books=test_books)

# @book_bp.route('/search')
# def search():
#     query = request.args.get("q", "").lower()
#     template_books = []
#     if query:
#         books = get_books_by_query(query)
#         for book in books['items']:
#             template_books.append(generate_book_from_g_data(book))
#     # Instead of JSON, return rendered HTML partial
#     return render_template("book-grid.html", books=template_books)



@book_bp.route("/update-bookshelf-order", methods=["POST"])
def update_bookshelf_order():
    data = request.get_json()
    g_id = data.get("g_id")
    position = data.get("position")
    if g_id is not None:
        optional_book = get_book_by_g_id(g_id)
        if optional_book:
            optional_book.shelf_pos = position
        else:
            return jsonify(success=False, body=f"No book found for {g_id}")
    db.session.commit()
    return jsonify(success=True, g_id=g_id, position=position)

@login_required
@book_bp.route("/update-book", methods=["POST"])
def update_book():
    logger.info(f'Form data: {request.form}')
    if request.method == 'POST' and current_user.is_authenticated:
        user_id = current_user.id
        g_id = request.form.get('g_id', None)
        status = request.form.get('status', None)
        owned = request.form.get('owned', None)
        logger.info(f'Updating book: {g_id} Status: {status} Owned: {owned}')
        outcome = update_user_book(g_id, current_user, status, owned)
        success = outcome[1] == 200
        return jsonify(success=success, g_id=g_id)

book_flask/src/templates/content/book-card.html
<div class="card mb-3 p-0" style="max-width: 350px;"
     role="button"
     data-bs-toggle="modal"
     data-bs-target="#bookModal"
     data-book="{{ v_book.to_json() }}">
    <div class="row g-0">
        <div class="col-md-4">
            {% if v_book.thumbnail != None %}
                <img src="{{ v_book.thumbnail}}" class="img-fluid rounded-start" style="max-height: 170px" alt="...">
            {% else %}
                <img src="{{ url_for('static', filename='images/empty_cover.png') }}" class="card-img-top" alt="no-thumnail">
            {% endif %}
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title overflow-hidden" style="max-height: 50px">{{ v_book.title }}</h5>
                <p class="card-text text-muted">By: {{ v_book.author }}</p>
                <span class="badge rounded-pill bg-secondary">{{ v_book.categories }}</span>
            </div>
        </div>
    </div>
</div>

book_flask/src/templates/content/book-modal.html
<!-- Book Modal -->
<div class="modal fade" id="bookModal" tabindex="-1" aria-labelledby="bookModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="bookTitle"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <!-- Tabs -->
                <ul class="nav nav-tabs" id="bookTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="settings-tab" data-bs-toggle="tab"
                                data-bs-target="#settings" type="button" role="tab"
                                aria-controls="settings" aria-selected="true">
                            Book Settings
                        </button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="extra-tab" data-bs-toggle="tab"
                                data-bs-target="#extra" type="button" role="tab"
                                aria-controls="extra" aria-selected="false">
                            Extra Book Info
                        </button>
                    </li>
                </ul>


                <div class="row">
                    <div class="col-4 ml-0 mb-0">
                        <img id="bookThumnail" src="{{ url_for('static', filename='images/empty_cover.png') }}" class="card-img-top" style="height: 400px" alt="no-thumnail">
                    </div>
                    <div class="col-8">
                        <div class="tab-content mt-3" id="bookTabContent">
                            <!-- Settings Tab -->
                            <div class="tab-pane fade show active" id="settings" role="tabpanel"
                                 aria-labelledby="settings-tab">
{#                            {{ url_for('book.update_book', next=next) }}#}
                                <form method="dialog" id="bookForm">
                                    <input type="hidden" name="g_id" id="hiddenGid" value="">
                                    <!-- Title & Author (read-only) -->
                                    <div class="mb-3">
                                        <label class="form-label">Title</label>
                                        <input id="titleInput" type="text" class="form-control" value="" disabled readonly>
                                    </div>

                                    <div class="mb-3">
                                        <label class="form-label">Author</label>
                                        <input id="authorInput" type="text" class="form-control" value="" disabled readonly>
                                    </div>

                                    <!-- Status Dropdown -->
                                    <div class="mb-3">
                                        <label class="form-label">Status</label>
                                        <select class="form-select" name="status" id="statusInput">
                                            {% for status in BookStatus %}
                                                <option value="{{ status.name }}">
                                                    {{ status.name }}
                                                </option>
                                            {% endfor %}
                                        </select>
                                    </div>

                                    <!-- Owned Checkbox -->
                                    <div class="form-check mb-3">
                                        <input class="form-check-input" type="checkbox" name="owned" id="ownedCheckbox"
                                               value="false"
                                        >
                                        <label class="form-check-label" for="ownedCheckbox">
                                            Owned
                                        </label>
                                    </div>
{#                                    {%  if current_user.is_authenticated==false %} disabled {% endif %}#}
                                    <button onclick="update_book();" class="btn btn-primary">Save</button>
                                </form>
                            </div>

                            <!-- Extra Info Tab -->
                            <div class="tab-pane fade" id="extra" role="tabpanel"
                                 aria-labelledby="extra-tab">
                                <div class="mt-3 overflow-auto" style="max-height: 400px">
                                    <strong>Description:</strong><p id="descriptionInput"></p>
                                    <strong>Page Count:</strong><p id="pageCountInput"></p>
                                    <strong>Published:</strong><p id="publishedInput"></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const bookModal = document.getElementById('bookModal');

        bookModal.addEventListener('show.bs.modal', event => {
            const card = event.relatedTarget; // The card that triggered the modal
            // Extract book data from card dataset
            const data = card.getAttribute('data-book');
            const book_data = JSON.parse(data)
            // Populate modal
            document.getElementById('bookTitle').textContent = book_data.title;
            document.getElementById('hiddenGid').value = book_data.g_id;
            document.getElementById('titleInput').value = book_data.title;
            document.getElementById('authorInput').value = book_data.author;
            document.getElementById('statusInput').value = book_data.status;

            if (book_data.owned){
                document.getElementById('ownedCheckbox').value = true
                document.getElementById('ownedCheckbox').checked = true
            }
            document.getElementById('bookThumnail').src = book_data.thumbnail;
            document.getElementById('descriptionInput').textContent = book_data.description;
            document.getElementById('pageCountInput').textContent = book_data.page_count;
            document.getElementById('publishedInput').textContent = book_data.publish_date;
        });
    });

    function update_book(){
        console.log('Updating book')
        const bookForm = document.getElementById('bookForm');
        let formData = new FormData(bookForm);
        fetch('/update-book', {
            method: "POST",
            {#body: formData#}
            body: formData
        }).then(response =>{
            if (!response.ok) {
                throw new Error("Network response was not ok");
            }
            const bookModal = document.getElementById('bookModal');
            const modalInstance = bootstrap.Modal.getInstance(bookModal);
            modalInstance.toggle()
            window.location.reload()
            return response.json();
        });
    }
</script>

book_flask/src/templates/content/login.html
<!doctype html>
<div class="modal fade" id="loginModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel">Login</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{{ url_for('auth.login') }}">
          <input type="text" name="username" placeholder="Username" required>
          <input type="password" name="password" placeholder="Password" required>
          <button type="submit">Login</button>
        </form>
      <a href="{{ url_for('auth.register') }}">Create User</a>
      </div>
    </div>
  </div>
</div>
{#<script>#}
{#    document.addEventListener('DOMContentLoaded', function() {#}
{#        var myModal = new bootstrap.Modal(document.getElementById('staticBackdrop'), {});#}
{#        myModal.show();#}
{#    });#}
{#</script>#}

book_flask/src/templates/content/register.html
<form method="POST">
    <input type="text" name="username" placeholder="Username" required>
    <input type="password" name="password" placeholder="Password" required>
    <button type="submit">Register</button>
</form>